export const IPC_CHANNELS = {
  bootstrap: "app:bootstrap",
  pickDirectory: "app:pickDirectory",
  readClipboardText: "app:readClipboardText",
  writeClipboardText: "app:writeClipboardText",
  getProjectWorkspace: "projects:getWorkspace",
  createProject: "projects:create",
  updateProject: "projects:update",
  deleteProject: "projects:delete",
  createTab: "tabs:create",
  renameTab: "tabs:rename",
  closeTab: "tabs:close",
  activateTab: "tabs:activate",
  resizeTab: "tabs:resize",
  writeToTab: "tabs:write",
  restartTab: "tabs:restart",
  listHistory: "history:list",
  recallHistory: "history:recall",
  terminalEvent: "terminal:event",
  setWindowTheme: "window:setTheme",
} as const;
