export const IPC_CHANNELS = {
  bootstrap: "app:bootstrap",
  pickDirectory: "app:pickDirectory",
  readClipboardText: "app:readClipboardText",
  writeClipboardText: "app:writeClipboardText",
  getProjectWorkspace: "projects:getWorkspace",
  createProject: "projects:create",
  updateProject: "projects:update",
  deleteProject: "projects:delete",
  createTab: "tabs:create",
  renameTab: "tabs:rename",
  closeTab: "tabs:close",
  applyLayoutPreset: "tabs:applyLayoutPreset",
  setFocusedSession: "tabs:setFocusedSession",
  activateSession: "sessions:activate",
  resizeSession: "sessions:resize",
  writeToSession: "sessions:write",
  restartSession: "sessions:restart",
  listHistory: "history:list",
  recallHistory: "history:recall",
  terminalEvent: "terminal:event",
  setWindowTheme: "window:setTheme",
} as const;
